// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUtWeVuHKgZkgZwoq34JashQgNBoAX5rI',
    appId: '1:496798876863:web:48567d15fd86295bae320a',
    messagingSenderId: '496798876863',
    projectId: 'aivivabot',
    authDomain: 'aivivabot.firebaseapp.com',
    storageBucket: 'aivivabot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlaawK7JuiOCts7f9oewrZ3RnVjq9Uacs',
    appId: '1:496798876863:android:2cfe01618af78aceae320a',
    messagingSenderId: '496798876863',
    projectId: 'aivivabot',
    storageBucket: 'aivivabot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjAnfTnZZM4ueSkYfqkFopr5ZZjK-DMeI',
    appId: '1:496798876863:ios:64a11a3c127088afae320a',
    messagingSenderId: '496798876863',
    projectId: 'aivivabot',
    storageBucket: 'aivivabot.firebasestorage.app',
    iosBundleId: 'com.example.aivivabot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUtWeVuHKgZkgZwoq34JashQgNBoAX5rI',
    appId: '1:496798876863:web:b72c57d7a391a4f2ae320a',
    messagingSenderId: '496798876863',
    projectId: 'aivivabot',
    authDomain: 'aivivabot.firebaseapp.com',
    storageBucket: 'aivivabot.firebasestorage.app',
  );
}
